### PR TITLE
Adding chili recipe 

### PR DESCRIPTION
**Pull request by HanaAbbas**

### CODE REVIEW

**Comment by ghost** [comment]
Thanks! How about also adding some salt?

**Comment by HanaAbbas** [comment]
Hey I added some honey! Please test in the test kitchen and let me know if it tastes good

**Comment by HanaAbbas** [comment]
Salt is already included in the chili spice packet. If you add more salt it will be oversalted :-1:

**Comment by ghost** [comment]
Okay, can you specify which cheese please?

**Comment by ghost** [comment]
LGTM:+1: Let's :ship:

**Pull request merged**
